- name: Run Backend API
  community.docker.docker_container:
    name: simple-api
    image: ghassenrezgui/tp-devops-simple-api:latest
    networks:
      - name: app-network
    env:
      SPRING_DATASOURCE_URL: "{{ vault_datasource_url }}"
      SPRING_DATASOURCE_USERNAME: "{{ vault_postgres_user }}"
      SPRING_DATASOURCE_PASSWORD: "{{ vault_postgres_password }}"
    pull: true
    recreate: true
  vars:
    ansible_python_interpreter: /opt/docker_venv/bin/python3
