name: Deployment
on:
  workflow_run:
    workflows: ["CI devops 2026"]
    types:
      - completed
    branches:
      - master

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          ssh-keyscan -H ghassen.rezgui.takima.school >> ~/.ssh/known_hosts

      - name: Run Ansible playbook
        run: |
            cd TPs/TP1/ansible
            echo "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > /tmp/vault_pass
            ansible-playbook -i inventories/setup.yml playbook.yml --vault-password-file /tmp/vault_pass
            rm /tmp/vault_pass